rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2

gazebo_ros_control:
  pid_gains:
    joint1: {p: 100, i: 0.01, d: 10.0}
    joint2: {p: 100, i: 0.01, d: 10.0}
