rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  ## Joint Trajectory Controller -------------------------------
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2

gazebo_ros_control:
  pid_gains:
    joint1: {p: 100, i: 0.01, d: 10.0}
    joint2: {p: 100, i: 0.01, d: 10.0}
